# Generated by Django 3.1.1 on 2020-10-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201024_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_profile_pic',
            field=models.FileField(blank=True, default='user_profile_images/default.PNG', null=True, upload_to='user_profile_images/'),
        ),
    ]
