# Generated by Django 3.1.1 on 2020-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201103_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_pic',
            field=models.ImageField(upload_to='location_pic/'),
        ),
    ]
