# Generated by Django 3.1.5 on 2021-02-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201103_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=30)),
                ('destination_pic', models.ImageField(upload_to='location_pic/')),
            ],
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
