# Generated by Django 3.1.5 on 2021-02-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210203_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='destination',
            name='destination_pic',
            field=models.ImageField(upload_to='destination_pic/'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_rent', models.IntegerField()),
                ('hotel_rating', models.IntegerField(default=0)),
                ('hotel_description', models.TextField()),
                ('hotel_pic', models.ImageField(upload_to='hotel_images/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.destination')),
                ('location', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
        ),
    ]
