# Generated by Django 3.1.5 on 2021-03-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210307_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='hotelroom',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='hotelroom',
            old_name='room_type_id',
            new_name='room_type',
        ),
        migrations.RenameField(
            model_name='hotelroomamenities',
            old_name='hotel_id',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='hotelroomamenities',
            old_name='hotel_room_id',
            new_name='hotel_room',
        ),
        migrations.RenameField(
            model_name='hotelroomamenities',
            old_name='room_amenities_id',
            new_name='room_amenities',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='user_id',
            new_name='user',
        ),
    ]
