# Generated by Django 3.1.5 on 2021-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210307_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='zip_code',
            field=models.IntegerField(choices=[(44600, '44600 Kathmandu'), (44800, '44800 Bhaktapur'), (44200, '44200 Chitwan')], default=True, unique=True),
        ),
    ]
