# Generated by Django 3.1.5 on 2021-03-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210307_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_total_capacity',
            field=models.IntegerField(default=True),
        ),
    ]
