# Generated by Django 3.1.5 on 2021-03-08 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210308_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 13, 36, 46, 471283)),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adult_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_child_guest',
            field=models.IntegerField(default=0),
        ),
    ]
