# Generated by Django 3.1.5 on 2021-03-08 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210308_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 20, 42, 55, 539646)),
        ),
        migrations.AlterField(
            model_name='hotelroomamenities',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel'),
        ),
    ]
