# Generated by Django 3.1.5 on 2021-03-12 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210309_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='room_total_capacity',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='total_capacity_of_adult_guest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='total_capacity_of_child_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 7, 34, 45, 884477)),
        ),
    ]
