# Generated by Django 3.1.5 on 2021-03-12 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210312_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 12, 12, 3, 19, 147560)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_adult_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='total_capacity_of_adult_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='total_capacity_of_child_guest',
            field=models.IntegerField(default=0),
        ),
    ]
