# Generated by Django 3.1.5 on 2021-03-18 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210315_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 19, 12, 55, 363584)),
        ),
    ]
