# Generated by Django 3.1.5 on 2021-03-19 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210318_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in_date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_date_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='isBookingExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 9, 27, 8, 7452)),
        ),
    ]
