# Generated by Django 3.1.5 on 2021-03-21 04:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0025_auto_20210319_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 21, 10, 7, 17, 103077)),
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2021, 3, 21, 10, 7, 17, 103077))),
                ('check_in_date_time', models.DateTimeField(default=None)),
                ('check_out_date_time', models.DateTimeField(default=None)),
                ('number_of_adult_guest', models.IntegerField(default=1)),
                ('number_of_child_guest', models.IntegerField(default=0)),
                ('no_of_room_booked', models.IntegerField(default=1)),
                ('isCanceled', models.BooleanField(default=False)),
                ('isBookingExpired', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
