# Generated by Django 3.1.5 on 2021-03-28 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210321_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='no_of_room_booked',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='no_of_room_booked',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 8, 47, 807435)),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 12, 8, 47, 808434)),
        ),
    ]
