# Generated by Django 3.1.5 on 2021-03-31 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210328_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isChecked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='isChecked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 9, 50, 31, 13928)),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 9, 50, 31, 14928)),
        ),
    ]
